Agregar  almacen de productos con categorias y seleccionar productos …
GersonDev/kotlin-erp pull request #2
Opened 2022-04-26 21:11 UTC by GersonDev

…para una futura venta
Porque? (Motivación: Cual es la razón para este cambio)
Poder seleccionar un producto para poder comprar
Que? (Contexto: Como se comportaba el código antes del cambio)
Agrege por el momento un menu con una opcion que seleciones 1 o mas productos
How? (Implementación: Que cambios se hicieron)
Se trabajo en la rama  feature/sales.Se agrego constantes ,el presenter,models,repositories,util
Evidencia (Screenshots/Video/Logs, etc.)

Checklist:
[] He creado/actualizado la documentación necesaria.
[ ] He agregado pruebas unitarias para cubrir mis cambios.
[x ] Todas las pruebas unitarias existentes siguen funcionando.

2022-04-26 22:04 UTC, CarlitosDroid requested changes

2022-04-26 22:04 UTC, CarlitosDroid commented on src/presentation/MenuPresenter.kt
> +        val cateries = categoriesRepository.getAllCategory()
Use a better name. Use `categories` instead of `cateries`

2022-04-26 22:04 UTC, CarlitosDroid commented on src/presentation/MenuPresenter.kt
> +        println("Desea elegir otro producto!")
Change `Desea elegir otro producto!` to `Desea elegir otro producto?`

2022-04-26 22:04 UTC, CarlitosDroid commented on src/util/Constants.kt
> +
Puedes encapsular una porcion de codigo con comentarios de este tipo `// region tu_titulo`  - `// endregion`

ejemplo

```
// region Constantes para Categorias
const val CATEGORY_PRODUCT_APPLIANCES = 1
const val CATEGORY_PRODUCT_BEDROOM = 2
const val CATEGORY_PRODUCT_WATERANDDRINKS = 3
const val CATEGORY_PRODUCT_TECHNOLOGIES = 4
const val CATEGORY_PRODUCT_BAKERYANDPASTRY = 5
const val CATEGORY_PRODUCT_GROCERY = 6
// endregion
```

2022-04-27 14:54 UTC, GersonDev commented
### Porque? (Motivación: Cual es la razón para este cambio)

*Para especificar la busqueda por tipo de categoria.

### Que? (Contexto: Como se comportaba el código antes del cambio)

*hacia una busqueda en genetar de todas las categorias y productos

### How? (Implementación: Que cambios se hicieron)

*se agrego una funcion showAllProductsByCategoryId para la busqueda de los productos por la categoria seleccionada

### Evidencia (Screenshots/Video/Logs, etc.)

*
![image](https://user-images.githubusercontent.com/45146217/165547510-32dab47f-4055-425b-99f6-552ce21c246b.png)


### Checklist:
[ ] He creado/actualizado la documentación necesaria.
[ ] He agregado pruebas unitarias para cubrir mis cambios.
[ ] Todas las pruebas unitarias existentes siguen funcionando.

2022-04-27 16:05 UTC, CarlitosDroid commented on src/Main.kt
> +    var excecuterunsubmainmenu = true
Usa `runCategorySubMenu` en vez de `excecuterunsubmainmenu`

2022-04-27 16:05 UTC, CarlitosDroid commented on src/presentation/MenuPresenter.kt
> +            println("${it.nombre}.\nmodelo o tipo:${it.modelo}.\n precio:${it.precio}")
Te falta imprimir tambien el `id`

2022-04-27 16:05 UTC, CarlitosDroid commented on src/Main.kt
> +                    menuPresenter.showAllProductsByCategoryId(selectedProductOption)
Te falta otra variable/readLine parecido a `selectedProductOption` para elegir el producto

2022-04-27 16:05 UTC, CarlitosDroid commented on src/Main.kt
> +                    selectedProductOption = readLine()!!.toInt()
Esta variable guarda la categoría seleccionada, no el producto. Por lo tanto no deberia llamarse `selectedProductOption` sino algo como `selectedCategoryOption`

2022-04-27 16:43 UTC, GersonDev commented
### Porque? (Motivación: Cual es la razón para este cambio)

*se cambio variables de selectedProductOption a selectedCategoryOption porque era de seleccion de categorias y en viceversa porque era seleccion de productos. Tambien agregamos el id a la visializacion de los productos

### Que? (Contexto: Como se comportaba el código antes del cambio)

*no habia la opcion de seleccion de producto

### How? (Implementación: Que cambios se hicieron)

*Se hicieron cambios en el main y menupresenter

### Evidencia (Screenshots/Video/Logs, etc.)

*
![image](https://user-images.githubusercontent.com/45146217/165575394-ce3a6405-8cca-45ab-a24e-150c7151dac5.png)
![image](https://user-images.githubusercontent.com/45146217/165575585-1379dc8e-5065-495b-8c7b-da2edd16f2b0.png)


### Checklist:
[ ] He creado/actualizado la documentación necesaria.
[ ] He agregado pruebas unitarias para cubrir mis cambios.
[ ] Todas las pruebas unitarias existentes siguen funcionando.

2022-04-27 16:53 UTC, CarlitosDroid approved these changes

2022-04-27 16:56 UTC, merged